### ISSUE TITLE
onStarup recalc rules for duration and interval timers

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/onboard#78]
When a user closes Firefox while either a duration or interval timer was running, we need to recalculate the time remaining on the next startup of the browser. Below is the suggested rules.

## 1 minute or less

* If there is a minute or less remaining of the duration timer, we abandon that timer and start a 24 hour interval timer.
* If there is a minute or less remaining of the interval timer, we abandon that timer and move on to the next notification

## > 1 minute

* If there is a minute or more remaining of the duration timer, we restart the timer for the remainder.
* If there is a minute or more remaining of the interval timer, we restart the timer for the remainder.

## Time elapsed since duration timer started > 24 hours

If more than 24 hours have elapsed since the duration timer was started::

* Start a new 24 hour interval timer, and add the last step to the missed snippets array

Thoughts @pdol @verdi?

**Comment by pdolanjski** [comment]
Starting a new 24 hour interval timer makes sense to me, but @verdi, what do you think?

**Comment by Verdi** [comment]
1 min or less & more than 1 min - these sound right to me. I think we can be more aggressive here though. If they are shutting Firefox down, how long is it likely to be before they restart it? At least a few minutes but probably more like hours? Maybe we make this threshold 1hr. What do you think @pdolanjski ? So if there is less than an hour to go when then shut down Firefox, just move on to the next step (next timer or next notification). If people get a new notification 23 hours later instead of 24, I don't think it violates the intention of the design.

Time elapsed since duration timer started > 24 hours - I think starting a new 24 hr interval timer is correct but we should also stick the notification into the missed array since it wasn't acted upon.

**Comment by schalkneethling** [comment]
I have updated the rules above. I left the first two at 1 minute until we have confirmation that we want to make it 1 hour.

**Comment by schalkneethling** [comment]
This landed in https://github.com/mozilla/onboard/pull/85
